### ISSUE TITLE
Undocumented exception in `isSpam` method

### ISSUE THREAD

**Issue by elliot-sawyer** [tijsverkoyen/Akismet#10]
https://github.com/tijsverkoyen/Akismet/blob/6f7987fe181fd0fddbc9832f2ddeaf088425c83f/Akismet.php#L367

If the network fails to contact Akismet, it will throw an exception with a 400 response. This leaves the method in a state where it returns neither true nor false.

An exception is also thrown if anyone of the $content, $author, $email or $url is marked as spam. This exception appears to be undocumented

**Comment by tijsverkoyen** [comment]
This is fixed with https://github.com/tijsverkoyen/Akismet/pull/11
